services:
  postgre:
    env_file: '.env'
    container_name: shopping_cart
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5423:5432'
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: